blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/fbratten/devops-automation-am/discussions
    about: Please use discussions for questions and feedback
  - name: 📧 Email Contact
    url: mailto:jack.bratten@adaptivearts.ai
    about: For private inquiries only
